### ISSUE TITLE
OpenError: A mutation operation was attempted on a database that did not allow mutations

### ISSUE THREAD

**Issue by alanshaw** [ipfs-shipyard/peer-pad#36]
Using Firefox private browsing tab. Doesn't happen in Chrome.

<img width="1274" alt="screen shot 2017-10-19 at 16 25 36" src="https://user-images.githubusercontent.com/152863/31779081-28c415de-b4ea-11e7-938c-2e1ac58ea12e.png">

**Comment by pgte** [comment]
AFAIK, private browsing in Firefox doesn't work with IndexedDB.
I think Peerpad core needs an API for feature detection...

**Comment by artus** [comment]
This issue can be closed, no? I had the same problem with Firefox (which is configured to never remember history -> FF defaults to incognito under the hood) and when switching to another browser, the issue did not happen. There is one remaining problem however, this error can't be catched with a `try-catch` block?

**Comment by jacobheun** [comment]
The error doesn't appear to be occurring anymore, and instead fails silently, so you can't actually do anything with PeerPad once you open a pad. I agree with @pgte that we should do some feature detection so that we can better inform the user. I created https://github.com/ipfs-shipyard/peer-pad-core/issues/18 to create support for that.

**Comment by pedro-nonfree** [comment]
Firefox seems relatively interested on solving this issue: https://bugzilla.mozilla.org/show_bug.cgi?id=781982
